name: opensense_sandbox
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.6
  # Some basic R packages
  - r-base=4.1.3
  - r-essentials
  - r-ggplot2
  - r-ncdf4
  - r-data.table
  - r-geosphere
  - r-sf
  - r-s2
  - r-TeachingDemos
  - r-gstat
  - r-hexbin
  - r-sfheaders
  - r-abind
  - r-stars
  # Some basic Python packages
  - numpy
  - matplotlib
  - pandas
  - xarray
  - dask
  - netcdf4
  # Additional dependencies for pycomlink
  - scipy
  - numba
  - h5py
  - shapely
  - pyproj
  - tqdm
  - pykrige
  - tensorflow
  - bottleneck
  - future
  # Additional dependencies for PyNNcml
  - cpuonly
  - pytorch