#!/bin/bash

OPENSENSE_SANDBOX="OPENSENSE_sandbox_outsource_environment"
SUBMODULS=("pws-pyqc", "PyNNcml", "pycomlink")

echo 'add Python submodules to path'
for sub_module in ${SUBMODULS[@]}; do
  python -c 'import sys; sys.path.append("${sub_module}")'
  #PYTHONPATH="${PYTHONPATH}:~/${OPENSENSE_SANDBOX}/${sub_module}"
done

export PYTHONPATH

echo 'PYTHONPATH=' ${PYTHONPATH}

echo ''
echo 'get content of submodules'
git submodule update --init

echo ''
echo 'done'

echo ''
echo 'Install RAINLINK'
cd RAINLINK
R CMD INSTALL RAINLINK*.tar.gz

echo ''
echo 'create dir in RAINLINK for figures'
mkdir Figures

# this must be the last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
