#!/bin/bash

OPENSENSE_SANDBOX="OPENSENSE_sandbox_outsource_environment"
SUBMODULS=("pws-pyqc", "PyNNcml")

for sub_module in ${SUBMODULS[@]}; do
  PYTHONPATH="${PYTHONPATH}:~/${OPENSENSE_SANDBOX}/${sub_module}"
done

export PYTHONPATH

echo 'PYTHONPATH=' ${PYTHONPATH}

echo ''
echo 'get content of submodules'
git submodule update --init

echo ''
echo 'done'

#exec "$@"
